name: Deploy to Development

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Build Website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm install
      - name: Install Parcel
        run: npm install -g parcel
      - name: Build the Website
        run: parcel build src/index.html
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: dist

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: github-pages
          path: dist
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
